### ISSUE TITLE
does it require to unlock the iphone ? (I lost my code)

### ISSUE THREAD

**Issue by MageScript** [mrlukyman/iphone-backup-extractor#1]

**Comment by mrlukyman** [comment]
This tool only works when you already have your device backed up on your computer. If you don't have any backup on your computer you wont be able to extract anything from the device itself with this tool.

**Comment by MageScript** [comment]
Ok so what's the purpose of that then ?

**Comment by mrlukyman** [comment]
To get data out of the backup. When you backup your iPhone with iTunes it encrypts the data so you can't see anything in the backup folder. Then you can restore the backup to your device through iTunes. But when you don't want to restore the data to your device, this tool can help you extract the data from the encrypted backup. You can for instance extract photos from the backup (or any other data).

I had a problem where I needed to extract photos from an old backup of my iPhone, but I didn't want to restore the whole backup as it was outdated. I was looking for a tool that could help me achieve this and I found this: https://www.iphonebackupextractor.com/ but it costs like 60 bucks and it was really just a single use for me so I didn't want to pay that much so I made this tool. It pretty much serves the same purpose except for the fancy features.

I hope I answered your question well. If you need any help with using the tool I'll be glad to help.

**Comment by MageScript** [comment]
Ok thank you !!
